/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una cuenta nueva */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar el par de tokens con el refresh token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado */
        get: operations["UsersController_findMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar el apodo */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas para la pantalla de avances */
        get: operations["UsersController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo completo de logros con bandera unlocked */
        get: operations["UsersController_achievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar metas del usuario, opcionalmente filtradas */
        get: operations["GoalsController_findAll"];
        put?: never;
        /** Crear una meta, opcionalmente con sus tareas */
        post: operations["GoalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sugerir tareas a partir del título de la meta */
        get: operations["GoalsController_suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una meta con sus tareas y evaluación */
        get: operations["GoalsController_findOne"];
        put?: never;
        post?: never;
        /** Eliminar una meta (borra en cascada tareas y evaluación) */
        delete: operations["GoalsController_remove"];
        options?: never;
        head?: never;
        /** Editar una meta (COMPLETADA no se acepta aquí, ver 409) */
        patch: operations["GoalsController_update"];
        trace?: never;
    };
    "/goals/{goalId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una tarea al final de la meta */
        post: operations["GoalTasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/tasks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reescribir el orden de las tareas de la meta */
        patch: operations["GoalTasksController_reorder"];
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar una tarea */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        /**
         * Editar una tarea
         * @description Al pasar status a COMPLETADA, la respuesta incluye goalProgress, streakCount, unlockedAchievements y goalReadyToEvaluate.
         */
        patch: operations["TasksController_update"];
        trace?: never;
    };
    "/goals/{goalId}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leer la evaluación de una meta */
        get: operations["EvaluationsController_findOne"];
        put?: never;
        /**
         * Guardar la evaluación de la meta
         * @description En la misma transacción marca la meta como COMPLETADA y evalúa logros.
         */
        post: operations["EvaluationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llave pública VAPID (ruta pública) */
        get: operations["PushController_getPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suscribir este dispositivo a notificaciones push */
        post: operations["PushController_subscribe"];
        /** Eliminar la suscripción de este dispositivo */
        delete: operations["PushController_unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar una notificación de prueba (solo si PUSH_TEST_ENABLED=true) */
        post: operations["PushController_sendTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/reminders/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disparar recordatorios (tareas que vencen mañana, rachas en riesgo) */
        post: operations["InternalController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio y de la conexión a la base de datos */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example Matías */
            nickname: string;
            /** @example matias@colegio.edu.co */
            email: string;
            /** @example miclave123 */
            password: string;
        };
        LoginDto: {
            /** @example matias@colegio.edu.co */
            email: string;
            /** @example miclave123 */
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        UpdateUserDto: {
            /** @example Mati */
            nickname: string;
        };
        CreateGoalDto: {
            /** @example Subir promedio a 4.5 */
            title: string;
            description?: string;
            /** @enum {string} */
            category: "ACADEMICA" | "PERSONAL" | "HABITO" | "PROFESIONAL";
            /**
             * @default MEDIA
             * @enum {string}
             */
            priority: "ALTA" | "MEDIA" | "BAJA";
            /**
             * Format: date
             * @example 2026-11-30
             */
            dueDate?: string;
            /**
             * @description Tareas a crear junto con la meta, en una sola transacción.
             * @example [
             *       "Crear un horario de estudio",
             *       "Repasar 3 veces por semana"
             *     ]
             */
            tasks?: string[];
        };
        UpdateGoalDto: {
            title?: string;
            description?: string;
            /** @enum {string} */
            category?: "ACADEMICA" | "PERSONAL" | "HABITO" | "PROFESIONAL";
            /** @enum {string} */
            priority?: "ALTA" | "MEDIA" | "BAJA";
            /**
             * Format: date
             * @example 2026-11-30
             */
            dueDate?: string;
            /**
             * @description COMPLETADA no se acepta aquí — devuelve 409. Solo se completa guardando la evaluación.
             * @enum {string}
             */
            status?: "ACTIVA" | "COMPLETADA" | "ARCHIVADA";
        };
        CreateTaskDto: {
            /** @example Crear un horario de estudio */
            title: string;
            /**
             * Format: date
             * @example 2026-09-15
             */
            dueDate?: string;
        };
        ReorderTasksDto: {
            /**
             * @description Todos los ids de tareas de la meta, en el nuevo orden.
             * @example [
             *       "uuid-3",
             *       "uuid-1",
             *       "uuid-2"
             *     ]
             */
            orderedIds: string[];
        };
        UpdateTaskDto: {
            title?: string;
            /** @enum {string} */
            status?: "PENDIENTE" | "EN_PROGRESO" | "COMPLETADA";
            /**
             * Format: date
             * @example 2026-09-15
             */
            dueDate?: string;
            position?: number;
        };
        CreateEvaluationDto: {
            /** @example 4 */
            rating: number;
            /** @example Cumplí el horario de estudio casi todas las semanas. */
            didWell: string;
            /** @example Me costó mantener el ritmo en semanas con muchos exámenes. */
            difficulties: string;
            /** @example Voy a planear con dos semanas de anticipación. */
            improvements: string;
        };
        PushKeysDto: {
            p256dh: string;
            auth: string;
        };
        SubscribePushDto: {
            /** @example https://web.push.apple.com/… */
            endpoint: string;
            keys: components["schemas"]["PushKeysDto"];
        };
        UnsubscribePushDto: {
            /** @example https://web.push.apple.com/… */
            endpoint: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_achievements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_findAll: {
        parameters: {
            query?: {
                status?: "ACTIVA" | "COMPLETADA" | "ARCHIVADA";
                category?: "ACADEMICA" | "PERSONAL" | "HABITO" | "PROFESIONAL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_suggestions: {
        parameters: {
            query?: {
                title?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalTasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalTasksController_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderTasksDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EvaluationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EvaluationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PushController_getPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PushController_subscribe: {
        parameters: {
            query?: never;
            header: {
                "user-agent": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribePushDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PushController_unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribePushDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PushController_sendTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InternalController_run: {
        parameters: {
            query?: never;
            header?: {
                /** @description Secreto del cron, no usa JWT */
                "x-cron-secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
